# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "stomp_out"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lee Kirchhoff"]
  s.date = "2015-01-23"
  s.description = "This implementation of STOMP is aimed at environments where a network connection, such as a WebSocket or TCP socket, is created and then raw data from that connection is passed to/from the STOMP client or server messaging layer provided by this gem."
  s.email = "support@rightscale.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/stomp_out.rb",
    "lib/stomp_out/client.rb",
    "lib/stomp_out/client_user.rb",
    "lib/stomp_out/errors.rb",
    "lib/stomp_out/frame.rb",
    "lib/stomp_out/heartbeat.rb",
    "lib/stomp_out/parser.rb",
    "lib/stomp_out/server.rb",
    "lib/stomp_out/server_user.rb",
    "stomp_out.gemspec"
  ]
  s.homepage = "https://github.com/rightscale/stomp_out"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Client and server for STOMP protocol that operate outboard of separately supplied network connection."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4"])
      s.add_runtime_dependency(%q<simple_uuid>, ["~> 0.2"])
      s.add_development_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_development_dependency(%q<faye-websocket>, ["~> 0.7"])
      s.add_development_dependency(%q<debugger>, ["~> 1.5"])
      s.add_development_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<right_develop>, ["~> 3.1"])
      s.add_development_dependency(%q<ruby-debug>, ["~> 0.10"])
    else
      s.add_dependency(%q<json>, ["~> 1.4"])
      s.add_dependency(%q<simple_uuid>, ["~> 0.2"])
      s.add_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_dependency(%q<faye-websocket>, ["~> 0.7"])
      s.add_dependency(%q<debugger>, ["~> 1.5"])
      s.add_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<right_develop>, ["~> 3.1"])
      s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4"])
    s.add_dependency(%q<simple_uuid>, ["~> 0.2"])
    s.add_dependency(%q<eventmachine>, ["~> 1.0"])
    s.add_dependency(%q<faye-websocket>, ["~> 0.7"])
    s.add_dependency(%q<debugger>, ["~> 1.5"])
    s.add_dependency(%q<flexmock>, ["~> 0.8"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<right_develop>, ["~> 3.1"])
    s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
  end
end

